version: '3'
services:
  pimod:
    build: ./pimod
    privileged: true
    tty: true
    volumes:
      - .:/tsOS-Base
      - ./pimod:/pimod
    working_dir: /tsOS-Base
    environment:
      - PATH:'$PATH:/pimod'
      - IMG
