services:
  pimod:
    image: nature40/pimod:v0.7.0
    privileged: true
    tty: true
    volumes:
      - .:/tsOS-Base
    working_dir: /tsOS-Base
    environment:
      - IMG
    command: pimod.sh tsOS-Base.Pifile
