name: Build tsOS-Base Images

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')

  build-arm64:
    runs-on: ubuntu-24.04
    needs: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.PAT_JONASHOECHST }}

      - name: Run tsOS-Base.Pifile
        uses: Nature40/pimod@v0.7.0
        with:
          pifile: tsOS-Base.Pifile

      - name: Package tsOS-Base-arm64-${{github.ref_name}}.zip
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mv tsOS-Base-arm64.img tsOS-Base-arm64-${{github.ref_name}}.img
          zip tsOS-Base-arm64-${{github.ref_name}}.zip tsOS-Base-arm64-${{github.ref_name}}.img

      - name: Upload Release tsOS-Base-arm64-${{github.ref_name}}.zip
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{github.ref_name}} tsOS-Base-arm64-${{github.ref_name}}.zip
